### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [59]:
df = pd.read_csv("C:\\Users\\khati\\GITHUB\\python\\dataset\\netflix_titles_2021.csv")


### Converting each column into numpy array

In [12]:
all_col = []
for colName in df:
    colName = df[colName].dropna().to_numpy()
    all_col.append(colName)

In [23]:
all_col[0].size

8807

### Column Name : Type

In [24]:
type_col = df['type'].dropna().to_numpy()
type_col

array(['Movie', 'TV Show', 'TV Show', ..., 'Movie', 'Movie', 'Movie'],
      shape=(8807,), dtype=object)

In [27]:
unique_type,count = np.unique(type_col,return_counts=True)
print(unique_type)
print(count)

['Movie' 'TV Show']
[6131 2676]


### Column Name: Country

In [36]:
country = df['country'].dropna().to_numpy()
country

array(['United States', 'South Africa', 'India', ..., 'United States',
       'United States', 'India'], shape=(7976,), dtype=object)

In [30]:
unique_type,count = np.unique(country,return_counts=True)
print(unique_type)
print(count)

[', France, Algeria' ', South Korea' 'Argentina'
 'Argentina, Brazil, France, Poland, Germany, Denmark' 'Argentina, Chile'
 'Argentina, Chile, Peru' 'Argentina, France'
 'Argentina, France, United States, Germany, Qatar' 'Argentina, Italy'
 'Argentina, Spain' 'Argentina, United States'
 'Argentina, United States, Mexico' 'Argentina, Uruguay, Serbia'
 'Argentina, Uruguay, Spain, France' 'Argentina, Venezuela' 'Australia'
 'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay'
 'Australia, Canada' 'Australia, France' 'Australia, France, Ireland'
 'Australia, Germany' 'Australia, India' 'Australia, Iraq'
 'Australia, New Zealand' 'Australia, New Zealand, United States'
 'Australia, United Arab Emirates' 'Australia, United Kingdom'
 'Australia, United Kingdom, Canada'
 'Australia, United Kingdom, United Arab Emirates, Canada'
 'Australia, United Kingdom, United States, New Zealand, Italy, France'
 'Australia, United Sta

In [32]:
type(unique_type)
unique_type.size

748

In [34]:
type(count)
count.size

748

### Column Name: Release Year

In [38]:
release_year = df['release_year'].dropna().to_numpy()
release_year

array([2020, 2021, 2021, ..., 2009, 2006, 2015], shape=(8807,))

In [42]:
release_year[:1000:10]

array([2020, 2021, 2021, 2021, 2021, 2014, 2010, 2021, 2021, 2019, 2019,
       2021, 2021, 2021, 2014, 1999, 1992, 1997, 2000, 2021, 2004, 2011,
       2021, 2021, 2021, 2020, 2020, 2021, 2021, 2021, 2021, 2021, 2021,
       2009, 2010, 2000, 2010, 2021, 2021, 2019, 2021, 2013, 2012, 2021,
       2021, 2009, 2007, 2021, 2020, 2021, 2021, 2016, 2021, 2015, 2020,
       2021, 2021, 2021, 2021, 2016, 1997, 2003, 2019, 2012, 2021, 2016,
       2021, 1981, 2020, 2021, 2021, 2021, 2021, 2021, 2014, 2021, 2015,
       2021, 2019, 2015, 2012, 1984, 2021, 2021, 2021, 2021, 2020, 2021,
       2021, 2021, 2021, 2021, 2020, 2010, 2014, 2009, 2021, 2011, 2015,
       2015])

#### Basic statistics 

In [54]:
print("Average Release Year:", np.mean(release_year))
print("Median Release Year:", np.median(release_year))
print("Oldest Movie Year:", np.min(release_year))
print("Newest Movie Year:", np.max(release_year))

Average Release Year: 2014.1801975701146
Median Release Year: 2017.0
Oldest Movie Year: 1925
Newest Movie Year: 2021


#### Find the Most Common Release Year

In [56]:
unique_years, counts = np.unique(release_year, return_counts=True)
most_common_year = unique_years[np.argmax(counts)]
print("Most Common Release Year:", most_common_year)


Most Common Release Year: 2018


#### Movies released after and befor 2018

In [57]:
after = release_year[release_year > 2018]
print("Movies released after 2018:", len(after))
before = release_year[release_year < 2018]
print("Movies released before 2018:", len(before))


Movies released after 2018: 2575
Movies released before 2018: 5085


### Column Name: Duration

In [52]:
duration = df['duration'].dropna().apply(lambda x: int(str(x).split(" ")[0]) if "min" in str(x) else np.nan).dropna().to_numpy()
duration = np.asarray(duration,dtype=int)
duration

array([ 90,  91, 125, ...,  88,  88, 111], shape=(6128,))

In [53]:
type(duration[0])

numpy.int64

#### Basic statistics 

In [55]:
print("Average Duration:", np.mean(duration))
print("Longest Movie Duration:", np.max(duration))
print("Shortest Movie Duration:", np.min(duration))

Average Duration: 99.57718668407311
Longest Movie Duration: 312
Shortest Movie Duration: 3


#### Movies longer than 120 mins

In [58]:
long_movies = duration[duration > 120]
print("Movies longer than 120 minutes:", len(long_movies))


Movies longer than 120 minutes: 1142
